FROM golang:alpine

RUN mkdir /build
WORKDIR /build

RUN apk update && apk add git

#RUN export GO111MODULE=off 
#RUN go get github.com/ArthurRanzini/HelloWorldGoDocker
RUN cd /build && git clone https://github.com/ArthurRanzini/HelloWorldGoDocker.git

EXPOSE 8080
ENTRYPOINT [ "/build/HelloWorldGoDocker/main" ]